"""Recreate all tables

Revision ID: 29a44cba94a3
Revises: 
Create Date: 2025-02-25 21:55:50.133400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a44cba94a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_title', sa.String(), nullable=True),
    sa.Column('recipe_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_recipes_id'), 'favorite_recipes', ['id'], unique=False)
    op.create_index(op.f('ix_favorite_recipes_recipe_title'), 'favorite_recipes', ['recipe_title'], unique=False)
    op.create_index(op.f('ix_favorite_recipes_recipe_url'), 'favorite_recipes', ['recipe_url'], unique=False)
    op.create_index(op.f('ix_favorite_recipes_user_id'), 'favorite_recipes', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_video_url'), 'favorites', ['video_url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('fridge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('expiration', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fridge_items_id'), 'fridge_items', ['id'], unique=False)
    op.create_index(op.f('ix_fridge_items_name'), 'fridge_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fridge_items_name'), table_name='fridge_items')
    op.drop_index(op.f('ix_fridge_items_id'), table_name='fridge_items')
    op.drop_table('fridge_items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_favorites_video_url'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_favorite_recipes_user_id'), table_name='favorite_recipes')
    op.drop_index(op.f('ix_favorite_recipes_recipe_url'), table_name='favorite_recipes')
    op.drop_index(op.f('ix_favorite_recipes_recipe_title'), table_name='favorite_recipes')
    op.drop_index(op.f('ix_favorite_recipes_id'), table_name='favorite_recipes')
    op.drop_table('favorite_recipes')
    # ### end Alembic commands ###
