"""Remove favorites table

Revision ID: a28ffe93714b
Revises: aec4c730835d
Create Date: 2025-03-01 17:45:32.241324

"""
from alembic import op
import sqlalchemy as sa

# Revision identifiers, used by Alembic.
revision = 'a28ffe93714b'
down_revision = 'aec4c730835d'
branch_labels = None
depends_on = None

def upgrade():
    op.drop_table('favorites')

def downgrade():
    op.create_table(
        'favorites',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('video_url', sa.String, nullable=False),
        sa.Column('title', sa.String, nullable=False),
        sa.Column('thumbnail_url', sa.String, nullable=False),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False),
    )





# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'a28ffe93714b'
# down_revision: Union[str, None] = 'aec4c730835d'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'favorites', type_='foreignkey')
#     # ### end Alembic commands ###
